import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import SocialApps from "../components/SocialApps";
import About from "../components/About";
import Skills from "../components/Skills";
import Experience from "../components/Experience";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className="flex flex-row-reverse mb-16">
					<button className="hover:opacity-50">
					<a href="#projects" className="px-12 text-4xl">
						Projects
					</a>
					</button>
					<button className="hover:opacity-50">
					<a href="#experience" className="px-12 text-4xl">
						Experience
					</a>
					</button>
					<button className="hover:opacity-50">
					<a href="#skills" className="px-12 text-4xl">
						Skills
					</a>
					</button>
				</div>
				<Banner />
				<SocialApps />
				<About />
				<Skills />
				<Experience />
			</main>
		</>
	);
}
